source ~/.vimrc.iav     " load my vim config

if has('nvim') && false " disabled cuz using AstroNvim now
    call plug#begin()
    Plug 'mrcjkb/haskell-tools.nvim'
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim', { 'branch': '0.1.x' }
    Plug 'neovim/nvim-lspconfig'

    "diagnostics
    Plug 'folke/trouble.nvim'

    " file tree
    Plug 'nvim-tree/nvim-web-devicons'
    Plug 'nvim-tree/nvim-tree.lua'

    " cmp
    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'hrsh7th/cmp-buffer'
    Plug 'hrsh7th/cmp-path'
    Plug 'hrsh7th/cmp-cmdline'
    Plug 'hrsh7th/nvim-cmp'

    " Themes
    Plug 'savq/melange-nvim'
    Plug 'AlexvZyl/nordic.nvim'
    call plug#end()
else
    packadd YouCompleteMe
endif


" System clipboard copy
" vmap <C-x> :!pbcopy<CR>  
vmap <C-c> :w !pbcopy<CR><CR>

set shell=$SHELL

if has('nvim') && false " disabled: using AstroNvim
    set termguicolors
    colorscheme melange
    nmap <Leader>tt :NvimTreeToggle<CR>
else
    colorscheme slate
endif

" Haskell language server

if !has('nvim') " for nvim I have installed https://github.com/mrcjkb/haskell-tools.nvim
    nnoremap <F1> :call LanguageClient_contextMenu()<CR>
    map <Leader>lk :call LanguageClient#textDocument_hover()<CR>
    map <Leader>lg :call LanguageClient#textDocument_definition()<CR>
    map <Leader>lr :call LanguageClient#textDocument_rename()<CR>
    map <Leader>lf :call LanguageClient#textDocument_formatting()<CR>
    map <Leader>lb :call LanguageClient#textDocument_references()<CR>
    map <Leader>la :call LanguageClient#textDocument_codeAction()<CR>
    map <Leader>ls :call LanguageClient#textDocument_documentSymbol()<CR>
    
    hi link ALEError Error
    hi Warning term=underline cterm=underline ctermfg=Yellow gui=undercurl guisp=Gold
    hi link ALEWarning Warning
    hi link ALEInfo SpellCap
endif

