"==============================
"	VIM CONFIG
"==============================

" General settings

" Set `nocompatible` to make Vim incompatible with Vi.
set nocompatible

" Disable backup files and swap files.
set nobackup
set noswapfile
set nowb

" Disable mouse (clicks and scrolls). Primarily for NeoVim
set mouse=

" Disable arrow key navigation.
nmap <Up> <Nop>
nmap <Left> <Nop>
nmap <Right> <Nop>
nmap <Down> <Nop>

" Leader keymap
let mapleader = "\<Space>"

" Terminal mode exit
tnoremap <C-w><C-w> <C-\><C-n><C-w><C-w>

" Unmap my tmux prefix key
nnoremap <C-s> <Nop>

" Fix backspace behavior.
set backspace=indent,eol,start

" Write the buffer
nnoremap <leader>w :w<CR>
nnoremap <leader>wq :wq<CR>
nnoremap <leader>wqa :wqa<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>qa :qa<CR>

" Enable autoread to reload files when they are changed.
set autoread

" Enable file type plugins to load different settings for different file types.
filetype plugin on

" Encoding settings

" Set the default encoding to UTF-8, CP1251 as backup.
set fileencodings=utf-8,cp1251

" Set the encoding to UTF-8.
set encoding=utf-8

" Tab settings
set ts=4
set shiftwidth=4
set expandtab

" Line break settings
set lbr " Set line breaks to be displayed as `=>\`.

" Highlight corresponding bracket to the one under cursor.
set showmatch

set wildmenu " Enable nice command autocomplete menu.
set splitbelow " Place new buffers below the current one.
set splitright " Place new buffers to the right of the current one.
set ssop+=resize " Save buffer positions and sizes when Vim exits.

" Interface settings
set number " Enable line numbers.
set wrap
set ruler " Display the cursor coordinates in the bottom right corner.
set showmode " Show the current mode in the status line.
set showcmd " Show the current command in the status line.
syntax on
set autoindent

" Search settings

" Ignore case by default, but use case-sensitive search if the search term contains uppercase letters.
set ignorecase
set smartcase
set hlsearch " Highlight search results.
set incsearch " Highlight search results as you type.

nnoremap <c-a> :let @/=""<CR>

" Visually highlight text
vnoremap <c-f> y<ESC>/<c-r>"<CR>


" Listchars

" Display spaces and tabs in list mode.
set listchars=tab:>-,trail:-

" LaTeX-Suite

" Enable Latex-Suite for LaTeX files.
filetype plugin on

" Set `shellslash` to ensure that LaTeX is called correctly on Windows.
set shellslash

" Set `grepprg` to always generate a file-name.
set grepprg=grep\ -nH\ $*

" Enable automatic indentation
filetype indent on

" Set the default filetype for empty LaTeX files to `tex`.
let g:tex_flavor='latex'

" Set the output file format to PDF.
let g:Tex_CompileRule_pdf='pdflatex -interaction=nonstopmode $*'
let g:Tex_DefaultTargetFormat='pdf'

" Other settings

" System clipboard copy
vmap <C-c> :w !pbcopy<CR><CR>

set shell=$SHELL

if !has('nvim')
    colorscheme slate
    syntax on " Enable syntax highlighting.
endif

" Using alt+backspace to delete a word in insert mode
" https://stackoverflow.com/a/73444171/9401508
" more info on mapping alt keys :help map-alt-keys
if has('gui_running')
    imap <M-BS> <C-w>
else
    imap <Esc><BS> <C-w>
endif

" Makefile bindings for Advent of Code
nmap <leader>mb :w<CR>:!make build<CR>
nmap <leader>mde :w<CR>:!make build && make debug < example.txt<CR>
nmap <leader>mdi :w<CR>:!make build && make debug < input.txt<CR>
nmap <leader>mre :w<CR>:!make build && make run < example.txt<CR>
nmap <leader>mri :w<CR>:!make build && make run < input.txt<CR>

" A possibility to plug in machine-specific configuration
if filereadable('~/.vimrc.local')
    source ~/.vimrc.local
endif
