export ZSH=~/.oh-my-zsh
ZSH_THEME="robbyrussell"

zstyle ':omz:update' mode reminder # just remind me to update when it's time
zstyle ':omz:update' frequency 13

export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export EDITOR='nvim'
export XDG_CONFIG_HOME=~/.config

source_if_exists() { [ -e $1 ] && source $1 || true; }

# Oh My Zsh and brew stuff

source_if_exists $ZSH/oh-my-zsh.sh
source_if_exists ~/.bash_profile

source_if_exists ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source_if_exists /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source_if_exists $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
eval "$(/opt/homebrew/bin/brew shellenv)"

plugins=(git zsh-autosuggestions)

# Zsh Autocompletion, taken from https://g3doc.corp.google.com/company/users/julienbc/cmdline/index.md?cl=head#command-line-setup
zstyle ':completion:*' menu yes select
zstyle ':completion::complete:*' use-cache 1        # enables completion caching
zstyle ':completion::complete:*' cache-path ~/.zsh/cache
autoload -Uz compinit && compinit -i

# Rc-file settings

rcfile=~/.zshrc

brc() { vim "${rcfile}"; }
brcup() { source "${rcfile}"; }
zrc() { vim ~/.zshrc; }
zrcup() { source ~/.zshrc && echo '.zshrc executed'; }

# functions / aliases

alias ls='eza -G'
alias ll='eza -lah'
alias tree='eza --tree'
alias cat='bat -p'

# other sources

source_if_exists ~/.travis/travis.sh # added by travis gem
source_if_exists ~/.ghcup/env # ghcup-env
source_if_exists ~/.config/envman/load.sh # envman

source_if_exists ~/.zshrc.work # work stuff

# This must be at the end of the file for sdkman to work!
export SDKMAN_DIR="$HOME/.sdkman"
source_if_exists ~/.sdkman/bin/sdkman-init.sh || true

